### ISSUE TITLE
사용할 라이브러리/언어/패키지

### ISSUE THREAD

**Issue by Jinjeok** [KwonHM/ijwgh#2]
사용할거 말해바
1. Node

**Comment by KwonHM** [comment]
사용할거 말해바

**Comment by Jinjeok** [comment]
난 서버 express밖에 모름

**Comment by murikubo** [comment]
뭘 써야지

목적이 없으니까 언어부터 고민되네

**Comment by KwonHM** [comment]
퇴근 타이머

**Comment by lunch1019** [comment]
php, jquery, ajax

**Comment by lunch1019** [comment]
걍 진규가 만든 케모노를 활성화시키자 (+db추가염)

**Comment by Jinjeok** [comment]
php 에반데 걍 ejs 쓰지

**Comment by lunch1019** [comment]
왜 에바야

**Comment by Jinjeok** [comment]
일단 역할을 나누자 너가 서버 나머진 클라이언트 난 js나 css, html 같은거 할게

**Comment by KwonHM** [comment]
너가 서버 나머진 클라이언트

**Comment by KwonHM** [comment]
난 js나 css?

**Comment by lunch1019** [comment]
글애

**Comment by Jinjeok** [comment]
@murikubo 넌 클라이언트 머할래

**Comment by lunch1019** [comment]
@murikubo 오 이런것도 되네

**Comment by Jinjeok** [comment]
멘션은 당근 돼야지

**Comment by Jinjeok** [comment]
* 마크다운도 먹히나? 먹히네

**Comment by lunch1019** [comment]
개신기

**Comment by Jinjeok** [comment]
[참고사이트](https://hitomi.la)

**Comment by lunch1019** [comment]
뒤질래

**Comment by Jinjeok** [comment]
# 또 머가 되더라
```html
<h1>이건가</h1>
```

**Comment by murikubo** [comment]
와 잠만 참고사이트 들어갔다가 좆될뻔했다

**Comment by lunch1019** [comment]
들어갔다가 ㅈ될뻔했잖아

**Comment by lunch1019** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by Jinjeok** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by lunch1019** [comment]
프론트는 둘이 알아서 나누셈

**Comment by Jinjeok** [comment]
css는 개빡시니까 같이 하자

**Comment by murikubo** [comment]
ㅇㅋ 나도 CSS에 붙음

**Comment by Jinjeok** [comment]
일단 브랜치를 나눠볼까

**Comment by KwonHM** [comment]
1. 사용자별로 나눈다
2. 목적별로 나눈다

**Comment by lunch1019** [comment]
노드나 php 설치 어케 했더라

**Comment by lunch1019** [comment]
목적별

**Comment by Jinjeok** [comment]
패키지.제이슨

**Comment by Jinjeok** [comment]
난 apt install node 하면 되는데

**Comment by Jinjeok** [comment]
짱도우는 모르겠다

**Comment by lunch1019** [comment]
집에서 찾아봐야지

**Comment by Jinjeok** [comment]
그럼 첫 기획은 퇴근 타이머?

**Comment by murikubo** [comment]
일하면서 퇴근을 조장하다니

<del>[천하의 개쌍놈](https://namu.wiki/w/%EC%B2%9C%ED%95%98%EC%9D%98%20%EA%B0%9C%EC%8C%8D%EB%86%88%EB%93%A4?from=%EC%B2%9C%ED%95%98%EC%9D%98%20%EA%B0%9C%EC%8C%8D%EB%86%88)</del>

<del>[칼퇴와는 다르다 칼퇴와는!](https://namu.wiki/w/%EC%9E%90%EC%BF%A0%EC%99%80%EB%8A%94%20%EB%8B%A4%EB%A5%B4%EB%8B%A4!%20%EC%9E%90%EC%BF%A0%EC%99%80%EB%8A%94!?from=%EC%9E%90%EC%BF%A0%EC%99%80%EB%8A%94%20%EB%8B%A4%EB%A5%B4%EB%8B%A4%20%EC%9E%90%EC%BF%A0%EC%99%80%EB%8A%94)</del>

**Comment by KwonHM** [comment]
퇴근타이머로 한다 :+1: 
다른 아이디어가 있다 :-1:

**Comment by lunch1019** [comment]
![image](https://user-images.githubusercontent.com/30451760/32039666-76687b8e-ba69-11e7-9230-87652061f333.png)

**Comment by lunch1019** [comment]
다행히 나무위키군

**Comment by Jinjeok** [comment]
걍 올리고 있으면 왼쪽 아래에 나와..

**Comment by lunch1019** [comment]
그러네 ㅎ

**Comment by Jinjeok** [comment]
빨리 결정해 심심하단 말야

**Comment by murikubo** [comment]
퇴근타이머면 야근 등의 변수가 있으면 ㅃㅃ 아님?

**Comment by murikubo** [comment]
당장 난 사장님 오늘 귀국이래서 엄청 불안함

**Comment by Jinjeok** [comment]
그래 그러면 이름을 바꾸자 - 칼퇴근타이머로

**Comment by murikubo** [comment]
좋아 좋지

**Comment by Jinjeok** [comment]
ㅇㅋ 브랜치 만듬

**Comment by lunch1019** [comment]
칼퇴타이머군

**Comment by lunch1019** [comment]
근데 나 익어 쓸줄 몰라

**Comment by Jinjeok** [comment]
git 배우고 와라

**Comment by Jinjeok** [comment]
근데 이거 하기 전에 기본 세팅을 끝내야 하지 않겠어?

**Comment by lunch1019** [comment]
집에서 해야될거가틍ㄴ데

**Comment by Jinjeok** [comment]
TODO:
* 서버 기본 설정 - express
* package.json 생성

**Comment by Jinjeok** [comment]
근데 왜 여기서 하지

**Comment by murikubo** [comment]
서버 설정 오네가이

**Comment by lunch1019** [comment]
express 해야돼?

**Comment by Jinjeok** [comment]
그게 더 쉬울걸

**Comment by lunch1019** [comment]
회사컴에서 설정해도 집에서 되나

**Comment by Jinjeok** [comment]
package.json만 잘만들면 집에서 클론해가지고 npm install하면 바로 됨

**Comment by lunch1019** [comment]
어렵군

**Comment by Jinjeok** [comment]
일단 .gitignore에 node_modules를 추가했으니 용량폭탄 맞을일은 없을 것

**Comment by Jinjeok** [comment]
필요한 모듈은 package.json의 dependencies에 넣어주세영

**Comment by lunch1019** [comment]
gohome0523

**Comment by lunch1019** [comment]
gohome0523@

**Comment by lunch1019** [comment]
maware
maware0523

**Comment by lunch1019** [comment]
maware.dothome.co.kr
maware0523
